contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #magmap channel"
    url: https://nfcore.slack.com/channels/magmap
    about: Discussion about the nf-core/magmap pipeline
